// The guided tour's script. Targets are data-tour="…" attributes in the pages.
export interface TourStep { target?: string; route?: string; title: string; text: string; tip?: string }

export const TOUR_STEPS: TourStep[] = [
  { title: "Welcome to the Eva KGDJ", text: "This graph is grounded in the institute's real, vetted research — but it was assembled with AI help, and almost none of it has been checked by a person yet. Treat every claim as a good first draft: approximately right, not yet verified. Finding what's wrong or missing, and building your own orientation graph (your portfolio) on top of it, is the actual work of this course. This tour takes two minutes; you can re-run it from the Help menu at any time." },
  { route: "/explore", target: "nav-explore", title: "Graph", text: "The canonical graph: nodes are theories, methods, topics, findings and concepts; edges say how they relate. Almost every node is dashed — nobody has checked it yet. That's the honest starting state of an AI-assembled graph, not a bug. Solid green means an editor confirmed it after real, identified review. Finding an error in a dashed node is exactly the kind of contribution this course rewards." },
  { route: "/explore", target: "filters", title: "Filters", text: "Narrow the graph by department, review status and node type, or search labels, descriptions and tags. Everything else on the page reacts to what is visible here." },
  { route: "/explore", target: "layout", title: "Layout and analysis", text: "Choose how the graph is arranged, then optionally switch on an analysis: centrality sizes nodes by how connected they are, communities colours clusters, shortest path lets you click two nodes and see the route between them. A line under the toolbar explains whichever one is active." },
  { route: "/explore", target: "canvas", title: "Select nodes", text: "Click a node to open it in the panel on the right. Hold Ctrl (or Shift / ⌘) and click to select several nodes and edges, or Ctrl+drag a box around them. A bar appears with 'Add to my portfolio' options for the selection.", tip: "Scroll to zoom, drag the background to pan, use Fit to come back." },
  { route: "/explore", target: "drawer", title: "Node panel", text: "Description, citations, connections and open proposals. Under 'reviews' anyone may review the node (never their own); under 'propose' you can propose an edit, a new connection or archival; 'add to my portfolio' forks it with your annotation." },
  { route: "/proposals", target: "nav-proposals", title: "Proposals", text: "Every change to the canonical graph goes through a proposal with a rationale and at least one citation. Anyone may review any proposal; editors decide when the reviews are sufficient. Submitters may stay anonymous; reviewers are always identified." },
  { route: "/portfolio", target: "nav-portfolio", title: "Portfolio", text: "Your own graph: forked canonical nodes with your annotations, plus your questions, resources, theories and methods, connected by one 'because' sentence each. Private by default; share with classmates for critique. Your instructor can see it." },
  { route: "/portfolio", target: "backup", title: "Back it up — every session", text: "The app makes no promise to keep your portfolio. Download a backup file at the end of every session (one click) and keep it with your course files; you can restore from it at any time. The report next to it compares the shape of your portfolio with your module's, anonymously." },
  { route: "/leaderboard", target: "nav-leaderboard", title: "Leaderboards", text: "Several boards, not one score: reviewing, submitting, annotating, bridging departments, asking questions, keeping a rhythm. Opt in from Account if you want to appear." },
  { route: "/account", target: "affiliation", title: "Account and affiliation", text: "Register your department, research group and module here, manage consent, export everything about you, or delete your account. Then go and fork your first node." },
];
