#!/usr/bin/env python3
"""Link mpi-eva-graph nodes to the real citations that ground them.

Prompted by a direct question (2026-09-09): does an mpi-eva-graph node's real
citation carry over when it enters KGDJ? Checked with eva-graph-66, who had just
built the citation layer on the mpi-eva-graph side: the answer is architectural, not
a bug. A node's own JSON record (mpi-eva-graph/sub-units/*/nodes/*.json, and the
mpi-eva-graph.json this repo's build_seed.py actually reads) carries no citation
field at all -- it never has. The real, curated citation-grounding edges (77 of them,
data/crosswalks/literature/eva-literature-groundings.yml, hand-verified against
eva_literature) live one layer up, materialized only in eva-index.json as
`meg:<node> -groundedIn-> oal:<openalex-id>` edges to a separate publication node.
Nothing was dropped in transit; KGDJ's seed simply never reached that layer.

This script reaches it. All 77 target OpenAlex works turn out to already be present
in kgdj.citations (build_literature_seed.py imports PuRe-matched eva_literature
works by openalex_id, and every one of these 77 curated targets is itself
PuRe-matched -- confirmed by checking the actual overlap, not assumed from the two
scripts sharing a source). So this is purely a linking step: no new citation rows,
just the kgdj.node_citations join the node's own file never carried.

    python apps/kgdj/supabase/seed/build_mpi_eva_graph_citations.py
    -> apps/kgdj/supabase/seed/0004_mpi_eva_graph_citations.sql

Run after 0001 (needs the nodes) and 0003 (needs the citations); a SELECT-based
insert makes it a no-op, not an error, for any edge whose node or citation isn't
present (matches build_ccp_module_seed.py's own convention for edges pointing at a
node that didn't import). Role is 'supports' -- node_citations' check constraint
doesn't have a 'grounds'/'evidences' option; 'supports' is the closest of the five
allowed values (defines/supports/contrasts/reviews/exemplifies) to what a
groundedIn edge actually means.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
EVA_INDEX = REPO / "ask_eva" / "eva-graph-pilot-app" / "ask-eva-app" / "data" / "eva-index.json"
OUT = HERE / "0004_mpi_eva_graph_citations.sql"


def q(s) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def main() -> int:
    idx = json.loads(EVA_INDEX.read_text(encoding="utf-8"))
    edges = [e for e in idx["edges"] if e.get("type") == "groundedIn" and e.get("s", "").startswith("meg:")]

    lines = [
        "-- Generated by supabase/seed/build_mpi_eva_graph_citations.py -- DO NOT EDIT BY HAND.",
        f"-- Source: eva-index.json's groundedIn edges from meg: nodes ({len(edges)} curated links,",
        "-- data/crosswalks/literature/eva-literature-groundings.yml). Links a node to a citation",
        "-- already present from 0003 -- no new kgdj.citations rows, only the join.",
        "",
    ]
    for e in edges:
        slug = e["s"].removeprefix("meg:")
        openalex_id = e["t"].removeprefix("oal:")
        note = (e.get("label") or "")[:400]
        lines.append(
            "insert into kgdj.node_citations (node_id, citation_id, role, note) "
            "select n.id, c.id, 'supports', "
            f"{q(note)} from kgdj.nodes n, kgdj.citations c "
            f"where n.slug = {q(slug)} and c.openalex_id = {q(openalex_id)} "
            "on conflict do nothing;"
        )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(edges)} node_citations links -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
